# -*- coding: utf-8 -*-
"""Predicts revenue_Linear Regression & Random Forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kTHw_jlOCgz6XHVKDBHY_xAEgYOdKnkb
"""

# Install required libraries
# !pip install pandas numpy scikit-learn matplotlib seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

# Sample Dataset: Company growth over years
data = {
    'Year': [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023],
    'Revenue ($M)': [5, 10, 15, 25, 40, 60, 85, 110, 150]  # Revenue over time
}

# Convert to DataFrame
# df = pd.DataFrame("/content/companies_data.csv") # Incorrect: This tries to create a DataFrame from a string path.
df = pd.DataFrame(data)  # Correct: Create DataFrame from the 'data' dictionary

# Prepare Features (X) and Target (y)
X = df[['Year']]
y = df['Revenue ($M)']

# Train-Test Split (80% Train, 20% Test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train Linear Regression Model
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

# Train Random Forest Model
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# **Predict Future Revenue for Next 5 Years (2024 - 2028)**
future_years = np.array([[2024], [2025], [2026], [2027], [2028]])
lr_future_preds = lr_model.predict(future_years)
rf_future_preds = rf_model.predict(future_years)

# **Visualization**
plt.figure(figsize=(10, 5))
sns.scatterplot(x=df['Year'], y=df['Revenue ($M)'], color='blue', label="Actual Revenue")
sns.lineplot(x=df['Year'], y=lr_model.predict(X), color='green', label="Linear Regression (Past)")
sns.lineplot(x=df['Year'], y=rf_model.predict(X), color='red', label="Random Forest (Past)")

# Plot Future Predictions
plt.plot(future_years, lr_future_preds, 'g--', label="Linear Regression (Future)")
plt.plot(future_years, rf_future_preds, 'r--', label="Random Forest (Future)")

plt.xlabel("Year")
plt.ylabel("Revenue ($M)")
plt.title("Company Revenue Prediction (2024-2028)")
plt.legend()
plt.show()

# Display Future Predictions
future_df = pd.DataFrame({'Year': future_years.flatten(),
                          'Linear Regression Prediction': lr_future_preds,
                          'Random Forest Prediction': rf_future_preds})
print(future_df)